
name: Deploy to another org after merge

on:
  pull_request:
    branches: [ "main" ]
    types: [closed]


jobs:
  deployAfterMerge:
    runs-on: ubuntu-latest

    steps:
        - name: 'Checkout source code'
          uses: actions/checkout@v2

        - uses: actions/setup-node@v2
          with:
              node-version: "14"

        - name: Install Salesforce CLI
          run: |
            wget https://developer.salesforce.com/media/salesforce-cli/sfdx-linux-amd64.tar.xz
            mkdir sfdx-cli
            tar xJf sfdx-linux-amd64.tar.xz -C sfdx-cli --strip-components 1
            ./sfdx-cli/install

        - name: 'Populate auth file with SECRET_URL'
          shell: bash
          run: 'echo ${{ secrets.SECRET_URL}} > SFDX_QA'
          
        - name: 'Authenticate to Integration Org'
          run: sfdx auth:sfdxurl:store -f SFDX_QA -s -a poductionOrg


        - name: 'Deploy source'
          id: Deploy
          run: sfdx force:source:deploy -x manifest/package.xml -u LRQA --json --loglevel fatal --checkonly -l RunLocalTests



